export default {
    test:'',
    origin: '',
    port: '',
    username: '',
    password: '',
    database: '',
    host: '',
    dbport: '',
    publicKey: '',
    privateKey: '',
    accessTokenTtl: '',
    refreshTokenTtl: '',
    saltWorkerFactor: '',
};
